name: CI

on: [pull_request]

jobs:
  compliance:
    name: NPM Audit Report
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4
      # Audit Package.json
      - name: NPM Audit Action
        uses: oke-py/npm-audit-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    needs: compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4.0.1
        with:
          node-version: '24.x'

      - run: npm ci --ignore-scripts

      - run: npm run lint
  circular-check:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4.0.1
        with:
          node-version: '24.x'

      - run: npm ci --ignore-scripts

      - name: Check for circular dependencies
        run: npm run circular
  build:
    needs: circular-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4.0.1
        with:
          node-version: '24.x'

      - uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/lib
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci --ignore-scripts

      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['24.x']
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/lib
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - run: npm ci --ignore-scripts

      - name: Test
        run: npm run test
  test-integration:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['24.x']
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - run: npm ci --ignore-scripts

      - name: Integration Tests
        run: npm run test:integration:only
